[theme]
primaryColor="#F63366" # Couleur dominante
backgroundColor="#FFFFFF" # Fond de page
secondaryBackgroundColor="#F0F2F6" # Fond des conteneurs
textColor="#262730" # Couleur du texte
font="sans serif" # Police